:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2017.3
:: Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

vivado  -notrace -mode batch -source run_ippack.tcl
