# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.3
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

#
# Settings for Vivado implementation flow
#
set top_module lstm_n5_16s_16b
set language verilog
set family virtexuplus
set device xcvu9p
set package -flga2104
set speed -2L-e-es1
set clock ap_clk
set fsm_ext "off"

# For customizing the implementation flow
set add_io_buffers false ;# true|false
